# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd7e11a2da0d695d32a3ffa182588503f9b76cae3c8eda8a38ad1015cccc49ec3db0fec0c0da9141aee738f117d6422a77febb5008b107001ee12e17aa269ac

test:
  secret_key_base: 95ea6f361588061cd065909f775c80a67fa04d77cf14444c71c904452c7739dc655b0aa16cb56e353886c6f5fefe07b57d2ad48976be8c631a4ecf809b5438c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
